---
- hosts: all

  tasks:
    - name: install ntpdate
        package:
        name: ntpdate
        state: present
    - name: install the latest version of Apache and MariaDB
        package:
            name:
            - httpd
            - mariadb-server
            state: latest
  