---
- hosts: localhost
  tasks:
    - name: install os libraries
      package:
        name:
          - ntp
          - xserver-xorg
          - x11-xserver-utils
          - xinit
          - openbox
          - chromium
          - fbi
          - ufw
          - unattended-upgrades
          - fail2ban
          - hostapd
          - dnsmasq
        state: present
    - name: openbox
      blockinfile:
        path: /etc/xdg/openbox/autostart
        block: |
          # Disable any form of screen saver / screen blanking / power management
          xset s off
          xset s noblank
          xset -dpms

          # Allow quitting the X server with CTRL-ATL-Backspace
          setxkbmap -option terminate:ctrl_alt_bksp
          /home/pi/kiosk-app.AppImage
    # - name: autologin pi user file
    #   path: /etc/systemd/system/getty@tty1.service.d
    #   state: file
    - name: autologin pi user directory
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: "0755"
    - name: autologin pi user
      blockinfile:
        create: true
        path: /etc/systemd/system/getty@tty1.service.d/autorun.conf
        block: |
          ExecStart=
          ExecStart=-/sbin/agetty --autologin ${USER} --noclear %I 38400 linux
