---
- hosts: localhost
  tasks:
    - name: Install OS libraries
      package:
        name:
          - ntp
          - xserver-xorg
          - x11-xserver-utils
          - xinit
          - openbox
          - chromium
          - fbi
          - ufw
          - unattended-upgrades
          - fail2ban
          - hostapd
          - dnsmasq
        state: present

    - name: Enable autostarting of Kiosk app [copy file]
      blockinfile:
        path: /etc/xdg/openbox/autostart
        block: |
          # Disable any form of screen saver / screen blanking / power management
          xset s off
          xset s noblank
          xset -dpms

          # Allow quitting the X server with CTRL-ATL-Backspace
          setxkbmap -option terminate:ctrl_alt_bksp
          /home/pi/kiosk-app.AppImage

    - name: Autologin Pi user [copy file]
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory

    - name: Autologin Pi user [enable service]
      copy:
        src: configs/autorun.conf
        dest: /etc/systemd/system/getty@tty1.service.d/autorun.conf

    - name: Splashscreen service [copy file]
      copy:
        src: configs/splashscreen.service
        dest: /etc/systemd/system/splashscreen.service

    - name: Splashscreen service [download image]
      get_url:
        url: https://kiosk-rpi-files.s3.eu-central-1.amazonaws.com/splashscreen.jpg
        dest: /home/pi/splashscreen.jpg

    - name: Splashscreen service [enable service]
      systemd:
        name: splashscreen
        enabled: yes

    - name: Boot configuration [copy file]
      copy:
        src: configs/config.txt
        dest: /boot/config.txt

    - name: Unattended upgrades [enable]
      copy:
        src: configs/50unattended-upgrades
        dest: /etc/apt/apt.conf.d/50unattended-upgrades

    - name: Kernel settings [copy file]
      copy:
        src: configs/cmdline.txt
        dest: /boot/cmdline.txt

    - name: Fail2ban config [copy file]
      copy:
        src: configs/jail.local
        dest: /etc/fail2ban/jail.local

    - name: Wifi service [copy file]
      copy:
        src: configs/rfkill-unblock-wifi.service
        dest: /etc/systemd/system/rfkill-unblock-wifi.service

    - name: Wifi service [enable]
      systemd:
        name: rfkill-unblock-wifi
        enabled: yes

    # - name: Download latest Kiosk is specified
    #   get_url:
    #     url: {{curl -s https://kiosk-app-files.s3.eu-central-1.amazonaws.com/alpha-linux-arm.yml | grep path | sed \'s|path: ||\' }}

    - name: Get Latest
      shell: |
        FILE=$(curl -s https://kiosk-app-files.s3.eu-central-1.amazonaws.com/alpha-linux-arm.yml | grep path | sed 's|path: ||')
        URL="https://kiosk-app-files.s3.eu-central-1.amazonaws.com/${FILE}"
        echo $URL
      register: latesturl

    - name: Download latest Kiosk is specified
      get_url:
        url: "{{ latesturl.stdout }}"
        dest: /home/pi/kiosk-app.AppImage
