---
- hosts: localhost
  tasks:
    - name: install os libraries
      package:
        name:
          - ntp
          - xserver-xorg
          - x11-xserver-utils
          - xinit
          - openbox
          - chromium
          - fbi
          - ufw
          - unattended-upgrades
          - fail2ban
          - hostapd
          - dnsmasq
        state: present
    - name: openbox
      blockinfile:
        path: /etc/xdg/openbox/autostart
        block: |
          # Disable any form of screen saver / screen blanking / power management
          xset s off
          xset s noblank
          xset -dpms

          # Allow quitting the X server with CTRL-ATL-Backspace
          setxkbmap -option terminate:ctrl_alt_bksp
          /home/pi/kiosk-app.AppImage
    - name: autologin pi user directory
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
    - name: autologin pi user
      copy:
        src: configs/autorun.conf
        dest: /etc/systemd/system/getty@tty1.service.d/autorun.conf
    - name: copy splashscreen service file
      copy:
        src: configs/splashscreen.service
        dest: /etc/systemd/system/splashscreen.service
    - name: download splashscreen
      get_url:
        url: https://kiosk-rpi-files.s3.eu-central-1.amazonaws.com/splashscreen.jpg
        dest: /home/pi/splashscreen.jpg
    - name: splashscreen service
      systemd:
        name: splashscreen
        enabled: yes
    - name: boot settings
      copy:
        src: configs/config.txt
        dest: /boot/config.txt
    - name: unattended upgrades
      copy:
        src: configs/50unattended-upgrades
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
    - name: kernel settings
      copy:
        src: configs/cmdline.txt
        dest: /boot/cmdline.txt
    - name: fail2ban config
      copy:
        src: configs/jail.local
        dest: /etc/fail2ban/jail.local
    - name: copy wifi service definition
      copy:
        src: configs/rfkill-unblock-wifi.service
        dest: /etc/systemd/system/rfkill-unblock-wifi.service
    - name: wifi service enable
      systemd:
        name: rfkill-unblock-wifi
        enabled: yes
