- name: Cleanup
  shell: |
    # Remove machine ID
    sudo rm /etc/machine-id
    sudo touch /etc/machine-id

    # Removing bash history and unsetting current session
    rm .bash_history
    history -c
