- name: Unattended upgrades [enable]
  copy:
    src: configs/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Fail2ban config [copy file]
  copy:
    src: configs/jail.local
    dest: /etc/fail2ban/jail.local

- name: Wifi service [copy file]
  copy:
    src: configs/rfkill-unblock-wifi.service
    dest: /etc/systemd/system/rfkill-unblock-wifi.service

- name: Wifi service [enable]
  systemd:
    name: rfkill-unblock-wifi
    enabled: yes

- name: Get Latest
  shell: |
    FILE=$(curl -s https://kiosk-app-files.s3.eu-central-1.amazonaws.com/alpha-linux-arm.yml | grep path | sed 's|path: ||')
    URL="https://kiosk-app-files.s3.eu-central-1.amazonaws.com/${FILE}"
    echo $URL
  register: latesturl

- name: Download latest Kiosk is specified
  get_url:
    url: "{{ latesturl.stdout }}"
    dest: /home/pi/kiosk-app.AppImage
    mode: "775"

- name: Remove machine id
  shell: |

- name: Cleanup
  shell: |
    # Remove machine ID
    sudo rm /etc/machine-id
    sudo touch /etc/machine-id

    # Removing bash history and unsetting current session
    rm .bash_history
    history -c
