- name: Enable X11 on startup
  blockinfile:
    path: /home/pi/.bashrc
    block: |
      [[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]] && startx -- -nocursor

- name: Enable autostarting of Kiosk app [copy file]
  blockinfile:
    path: /etc/xdg/openbox/autostart
    block: |
      # Disable any form of screen saver / screen blanking / power management
      xset s off
      xset s noblank
      xset -dpms

      # Allow quitting the X server with CTRL-ATL-Backspace
      setxkbmap -option terminate:ctrl_alt_bksp
      /home/pi/kiosk-app.AppImage
