- name: Enable X11 on startup
  blockinfile:
    path: /home/pi/.bashrc
    block: |
      [[ -z $DISPLAY && $XDG_VTNR = 1 ]] && startx -- -nocursor

- name: Enable autostarting of Kiosk app [copy file]
  copy:
    src: autostart
    dest: /etc/xdg/openbox/autostart
