- name: Unattended upgrades [enable]
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Fail2ban config [copy file]
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local

- name: Wifi service [copy file]
  copy:
    src: rfkill-unblock-wifi.service
    dest: /etc/systemd/system/rfkill-unblock-wifi.service

- name: Wifi service [enable]
  systemd:
    name: rfkill-unblock-wifi
    enabled: yes
