- name: Install OS libraries
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - ntp
    - xserver-xorg
    - x11-xserver-utils
    - xinit
    - openbox
    - chromium
    - fbi
    - ufw
    - unattended-upgrades
    - fail2ban
    - hostapd
    - dnsmasq
